title: Pierre Baudoux
email: mail@pbaudoux.com
description: >-
  Random tech toughts
baseurl: ""
url: "https://pbaudoux.com"
twitter_username: pierrebaudoux
github_username:  pbaudoux
linkedin_username: pbaudoux

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji

header_pages:
  - books.md
  - misc.md
  - about.md
